### ISSUE TITLE
DLATK issue with generating a pickle file

### ISSUE THREAD

**Issue by meowmi123** [dlatk/dlatk#5]
Hi, 
this is my first time trying this DLA tutorial and finished up till the step of using one of our data driven lexica to make predictions from out text data by running the following command:
dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_lex_table -l dd_emnlp14_ageGender --weighted_lexicon

then i proceeded on to generate a pickle file using the following commands:
1) dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --f feat$1gram$messages_en$user_id$16to16$0_01 --outcome_table blog_outcomes --outcomes age --train_regression --save_model --picklefile deleteMe.pickle --nostandardize --regression_to_lexicon testAgeLex

2) dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --f feat$1gram$messages_en$user_id$16to16$0_01 --load_model --picklefile deleteMe.pickle --regression_to_lexicon testAgeLex

this 2 commands did generate a new leixon table under the permalexicon db which consists of the following columns, (id, term, category, weight)

may i know am i on the right track to produce the lexicon.json file to insert back to a webservice ?

or am i missing any steps in between?

**Comment by sjgiorgi** [comment]
There are two ways of building predictive models with dlatk: pickles (with --save_model and --picklefile) and lexica (with --regression_to_lexicon). So your first command is actually doing both. You could split that command into two:

1.  dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --f feat$1gram$messages_en$user_id$16to16$0_01 --outcome_table blog_outcomes --outcomes age --train_regression --save_model --picklefile deleteMe.pickle

2.  dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --f feat$1gram$messages_en$user_id$16to16$0_01 --outcome_table blog_outcomes --outcomes age --nostandardize --regression_to_lexicon testAgeLex --train_regression

The first one will save an instance of a RegressionPredictor object inside the file "deleteMe.pickle" which you can then load within dlatk (and only dlatk) and predict values on a new dataset. The second one will produce a MySQL table called "testAgeLex", as you saw. You can also load this within dlatk (and use to predict values on a new dataset) but this format is more general as you only have words with weights (as opposed to a pickled Python object). 

When creating predictive lexica you are limited to using only 1gram features and regression algorithms that have linear coefficients. This has two benefits: the output format is both standard across multiple disciplines (see LIWC for example) and the lexicon is interpretable as you can see which words drive your predictions. 

Pickles, on the other hand, allow for multiple feature sets / feature types, any regression model and advanced feature selection pipelines. This can drastically increase your predictive power at the cost of interpretability and extensibility. Here you lose interpretability since you aren't limited to just single words (think clustered words, part of speech ngrams, character ngrams, extra-linquistic features, etc.). Finally, pickles have limited use since you are saving a dlatk object and therefore they can only be used within this package. 

If you want a predictive lexicon you can run the second command above. You can then predict values on a new data set within dlatk using 

dlatkInterface.py -d dla_tutorial -t msgs_new_data -c user_id --add_lex_table -l testAgeLex --weighted_lexicon

If you want to take the MySQL table and save to a json you can use the mysqlToJSON script [here](https://github.com/dlatk/usefulScripts).

I realize the sample commands in the documentation are a little misleading. I will add more details on how to create a predictive lexicon. You should also read the [three prediction tutorials](http://dlatk.wwbp.org/tutorials.html).

**Comment by meowmi123** [comment]
Hi, 
Thank you for enlightening and giving guidance on the commands to use and also the useful links
Your reply is indeed useful for me to move on to my next step =)

Thank you for your help!

**Comment by meowmi123** [comment]
Hi! i have some other questions for you regarding this DLATK :)
1. Is it possible for more than 1gram for predictive lexica?  and for the scores to be a more readable range, do you do any specific steps such as normalizing it so that it lies within a range of -1 to 1 
- If using model has more predictive power, we might need to package this as a service as opposed to using nodeJS?

2. Do you think it is possible to package dlatk predict functionality as a http service? 

3. Is there any way there this outcome will not be limited to a bag of words outcome after generating it as a json file

Thank you for your help in this :)

**Comment by sjgiorgi** [comment]
1. Yes, it is possible to build multiword lexica. The Spanish PERMA lexicon distributed with this package contains 1 and 2-grams. One thing to keep in mind when building multiword lexica is that dlatk defaults to your 1gram table when you apply the lexicon. See the [Intro Prediction / Classification / Predictive Lexica](http://dlatk.wwbp.org/tutorials/tut_pred.html) for how to apply your lexicon. In this example we apply the age/gender lexicon using the following command:

`dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_lex_table -l dd_emnlp14_ageGender --weighted_lexicon` 

Under the hood we are querying the 1gram table `feat$1gram$msgs_xxx$user_id$16to16`. When applying a multiword lexicon you need to override the default word table with the `--word_table` flag. For example, when applying the Spanish PERMA lexicon you would use the 1to2gram table:

`dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_lex_table -l dd_sperma_v2 --weighted_lexicon --word_table 'feat$1to2gram$msgs_xxx$user_id$16to16'` 

You could manually standardize the weights to be between -1 and 1 but this doesn't happen within dlatk and I can't comment on how that would influence results downstream.

2. This could be done but a) dlatk wasn't built for real time analysis, b) dlatk is pretty bulky and has a lot of dependencies and c) dlatk needs MySQL . All the web apps we have built use a streamlined version of dlatk with minimal dependencies, no MySQL and custom code.

3. Sorry but I don't follow this question.

**Comment by meowmi123** [comment]
Hi, thank you for your reply,
i have been trying to generate a new set of lexical json file based on another set of data to predict on another 5 classifiers, however i have a few questions to ask 
1) the permalexicon sample database which consists of various dataset : dd_emnlp14_agegender, dd_testagelex , met_a30_2000_cp
can i clarify that the table of dd_emnlp14_agegender and dd_testagelex are generated based on the mallet?
i been trying to use mallet to generate the data driven lexica so as to make predictions from out text data

however i been encountering the following error message::
_Traceback (most recent call last):
  File "dlatkInterface.py", line 1834, in <module>
    main()
  File "dlatkInterface.py", line 904, in main
    mt.addLDAMessages(args.addldamsgs)
  File "D:\dlatk\dlatk\messageTransformer.py", line 130, in addLDAMessages
    currentLDA = dict( [(ldaColumnLabels[i], fields[i]) for i in  labelRange])
  File "D:\dlatk\dlatk\messageTransformer.py", line 130, in <listcomp>
    currentLDA = dict( [(ldaColumnLabels[i], fields[i]) for i in  labelRange])
IndexError: list index out of range_


i am stuck with this specific command in the mallet tutorial:
https://dlatk.wwbp.org/tutorials/tut_lda.html

command : dlatkInterface.py -d dla_tutorial -t msgs_lda_tok --add_lda_messages  ~/lda_tutorial/lda_topics

for every new dataset that i want to predict the age/gender/ other classifiers , i have to run through the mallet process right in order to generate out the respective lexica table?

2) met_a30_2000_cp -> this table, this is the one which look up to the 2000 fb topics? is it ok to reuse this particular table regardless of what i am predicting? or am i supposed to generate out a brand new one everytime i want to predict a new dataset?

i did managed to generate out a lda_topics file based on the content run against the dlatkInterface file as provided in the tutorial, however when i was trying to execute the Step 6: Import state file into database, i faced with the error listed above.


for the DLATK tutorial, i am trying to execute this following step: dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_lex_table -l dd_emnlp14_ageGender --weighted_lexicon

however stuck with the missing table dd_emnlp14_ageGender, as i am trying to replace this table with the lexica table using mallet for the 5 classifiers which im trying to predict by using DLATK .
